name: Lua-NOGC CI

on:
  push:
    branches: [ Lua5.3.5-NOGC ]
  pull_request:
    branches: [ Lua5.3.5-NOGC ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: build and test
      run: make linux test
